"""
V4.4.2 Showable Output Report

Creates/updates a Google Sheet tab named AutomationOutput.
This is designed for screenshots/client/developer sharing.
"""

import argparse
import os
from collections import Counter

import collector as core


REPORT_HEADERS = ["Section", "Metric", "Value", "Notes"]


def rows_to_records(values):
    if not values:
        return []
    headers = values[0]
    return [core.row_to_record(headers, row) for row in values[1:]]


def count_by(records, field):
    return Counter(core.clean_text(r.get(field) or "Blank") for r in records)


def source_counts(sources):
    c = Counter(core.clean_text(s.get("status") or "Blank") for s in sources)
    ats = sum(1 for s in sources if core.clean_text(s.get("source_type") or "").startswith("ATS "))
    fresh = sum(1 for s in sources if core.clean_text(s.get("source_type") or "") == "Fresh Job Signal")
    direct = sum(1 for s in sources if core.clean_text(s.get("source_type") or "") == "Fresh Direct Job Page")
    discovered = sum(1 for s in sources if core.clean_text(s.get("source_type") or "") == "Discovered Website")
    linkedin_signal = sum(1 for s in sources if "linkedin company-listed signal" in core.clean_text(s.get("discovered_from") or "").lower())
    return c, ats, fresh, direct, discovered, linkedin_signal


def count_fake_rows(records):
    total = 0
    for r in records:
        try:
            if core.meta_record_vacancy_reject_reason(r, None) or core.is_hard_fake_job_record(r):
                total += 1
        except Exception:
            try:
                if core.meta_record_vacancy_reject_reason(r, None):
                    total += 1
            except Exception:
                pass
    return total


def build_report(sheet1, sources, meta, workflow_name):
    stamp = core.now_ist().isoformat(timespec="seconds")
    open_jobs = [
        r for r in sheet1
        if core.clean_text(r.get("status") or "").lower() == "publish"
        and core.clean_text(r.get("filled") or "").lower() != "yes"
    ]
    active_meta = [
        r for r in meta
        if core.clean_text(r.get("Status") or "").lower() == "active"
        and core.clean_text(r.get("Application Status") or "").lower() == "open"
    ]

    status_counts, ats_count, fresh_count, direct_count, discovered_count, linkedin_signal_count = source_counts(sources)

    rows = []
    rows.append(["Overview", "Report generated", stamp, "Asia/Kolkata time"])
    rows.append(["Overview", "Workflow", workflow_name, "Generated by V4.4.6"])
    rows.append(["Overview", "Website-ready open jobs", len(open_jobs), "Rows currently publishable from Sheet1"])
    rows.append(["Overview", "Internal active jobs", len(active_meta), "Open rows in _CollectorMeta"])
    rows.append(["Overview", "Total sources", len(sources), "Includes active, warning and rejected"])
    rows.append(["Overview", "Active sources", status_counts.get("Active", 0), "Eligible for hourly checking"])
    rows.append(["Overview", "Warning sources", status_counts.get("Warning", 0), "Temporary check failures"])
    rows.append(["Overview", "Rejected sources", status_counts.get("Rejected", 0), "Blocked from hourly checking"])
    cleaned_fake_rows = sum(
        1 for r in meta
        if "v4.4.5 hard cleanup" in core.clean_text(r.get("Closed Reason") or "").lower()
    )
    rows.append(["Overview", "Cleaned fake rows", cleaned_fake_rows, "Old HomeLane/AECOM/service rows closed by hard cleanup"])
    rows.append(["Overview", "ATS sources", ats_count, "Rows where source_type starts with ATS"])
    rows.append(["Overview", "Fresh Job Signal sources", fresh_count, "Sources found by fresh-job workflow"])
    rows.append(["Overview", "Fresh Direct Job Page sources", direct_count, "Direct pages verified as job pages"])
    rows.append(["Overview", "LinkedIn company-listed signals resolved", linkedin_signal_count, "LinkedIn used as signal only; final apply is official/non-LinkedIn"])
    rows.append(["Overview", "Discovered Website sources", discovered_count, "Sources found by daily discovery"])

    rows.append(["", "", "", ""])

    for company, count in count_by(open_jobs, "employer_name").most_common(20):
        rows.append(["Jobs by employer", company, count, "Published job count"])

    rows.append(["", "", "", ""])

    for category, count in count_by(open_jobs, "category").most_common(20):
        rows.append(["Jobs by category", category, count, "Published job count"])

    rows.append(["", "", "", ""])

    for apply_type, count in count_by(open_jobs, "apply_type").most_common(10):
        rows.append(["Apply type", apply_type, count, "email / external"])

    rows.append(["", "", "", ""])

    for r in open_jobs[:30]:
        rows.append([
            "Live jobs",
            core.clean_text(r.get("title") or ""),
            core.clean_text(r.get("employer_name") or ""),
            " | ".join(
                x for x in [
                    core.clean_text(r.get("location") or ""),
                    core.clean_text(r.get("category") or ""),
                    core.clean_text(r.get("apply_type") or ""),
                    core.clean_text(r.get("expiry_date") or ""),
                ]
                if x
            ),
        ])

    rows.append(["", "", "", ""])

    recent_sources = [
        s for s in sources
        if core.clean_text(s.get("source_type") or "") != "Seed Website"
        and core.clean_text(s.get("status") or "") in ("Active", "Warning", "New")
    ][-25:]
    for s in recent_sources:
        rows.append([
            "Recent accepted sources",
            core.clean_text(s.get("company_name") or ""),
            core.clean_text(s.get("source_type") or ""),
            core.clean_text(s.get("career_url") or ""),
        ])

    rows.append(["", "", "", ""])

    rejected = [
        s for s in sources
        if core.clean_text(s.get("status") or "") == "Rejected"
    ][-25:]
    for s in rejected:
        rows.append([
            "Rejected source examples",
            core.clean_text(s.get("company_name") or ""),
            core.clean_text(s.get("quality_reason") or ""),
            core.clean_text(s.get("career_url") or ""),
        ])

    return [REPORT_HEADERS] + rows


def update_report(workflow_name):
    sheet_id = os.environ.get("GOOGLE_SHEET_ID", "")
    if not sheet_id:
        raise RuntimeError("Missing GOOGLE_SHEET_ID")

    sheet_tab = os.environ.get("GOOGLE_SHEET_TAB", "Sheet1")
    source_tab = os.environ.get("GOOGLE_SOURCES_TAB", "Sources")
    meta_tab = os.environ.get("GOOGLE_META_TAB", "_CollectorMeta")
    report_tab = os.environ.get("GOOGLE_REPORT_TAB", "AutomationOutput")

    svc = core.sheet_service()

    sheet1 = rows_to_records(core.read_sheet_values(svc, sheet_id, sheet_tab))
    sources = rows_to_records(core.read_sheet_values(svc, sheet_id, source_tab))
    meta = rows_to_records(core.read_sheet_values(svc, sheet_id, meta_tab))

    output = build_report(sheet1, sources, meta, workflow_name)

    core.get_sheet_properties(svc, sheet_id, report_tab, create_if_missing=True)
    core.ensure_sheet_columns(svc, sheet_id, report_tab, len(REPORT_HEADERS))

    svc.spreadsheets().values().clear(
        spreadsheetId=sheet_id,
        range=f"'{report_tab}'!A:Z",
        body={},
    ).execute()
    svc.spreadsheets().values().update(
        spreadsheetId=sheet_id,
        range=f"'{report_tab}'!A1:D{len(output)}",
        valueInputOption="RAW",
        body={"values": output},
    ).execute()

    print("=" * 80)
    print(f"AutomationOutput report updated: {len(output)-1} rows")
    print(f"Open website jobs: {len(sheet1)}")
    print(f"Sources: {len(sources)}")
    print("=" * 80)


def self_test():
    sample_jobs = [
        {
            "title": "Junior Architect",
            "status": "publish",
            "filled": "no",
            "employer_name": "Example Architects",
            "category": "Architecture",
            "apply_type": "email",
            "location": "Mumbai|India",
            "expiry_date": "18-09-2026",
        }
    ]
    sample_sources = [
        {"status": "Active", "source_type": "Seed Website", "company_name": "Example", "career_url": "https://example.com/careers"},
        {"status": "Rejected", "source_type": "Fresh Job Signal", "company_name": "Bad Platform", "quality_reason": "Blocked platform/domain", "career_url": "https://bad.example"},
        {"status": "New", "source_type": "ATS Lever", "company_name": "Example", "career_url": "https://jobs.lever.co/example"},
        {"status": "New", "source_type": "Fresh Job Signal", "company_name": "LinkedIn Example", "discovered_from": "LinkedIn company-listed signal only; final apply is official/non-LinkedIn", "career_url": "https://example.com/careers"},
    ]
    report = build_report(sample_jobs, sample_sources, [], "self-test")
    assert report[0] == REPORT_HEADERS
    joined = "\\n".join(" ".join(map(str, row)) for row in report)
    assert "Website-ready open jobs" in joined
    assert "Junior Architect" in joined
    assert "ATS sources" in joined
    assert "Rejected source examples" in joined
    assert "LinkedIn company-listed signals resolved" in joined
    print("REPORT OUTPUT SELF TEST PASSED")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--self-test", action="store_true")
    parser.add_argument("--workflow", default="manual")
    args = parser.parse_args()

    if args.self_test:
        self_test()
        return

    update_report(args.workflow)


if __name__ == "__main__":
    main()
