"""
V5 Showable Output Report

Creates/updates AutomationOutput, including Verified jobs + CandidateJobs pipeline metrics.
"""

import argparse
import os
from collections import Counter

import collector as core

REPORT_HEADERS = ["Section", "Metric", "Value", "Notes"]


def rows_to_records(values):
    if not values:
        return []
    headers = values[0]
    return [core.row_to_record(headers, row) for row in values[1:]]


def read_records_safe(svc, sheet_id, tab):
    try:
        return rows_to_records(core.read_sheet_values(svc, sheet_id, tab))
    except Exception:
        return []


def ctext(v):
    return core.clean_text(v or "")


def count_by(records, field):
    return Counter(ctext(r.get(field) or "Blank") for r in records)


def count_fake_rows(records):
    n = 0
    for r in records:
        try:
            job = {
                "title": r.get("title") or r.get("Job Title") or r.get("Title") or "",
                "description": r.get("description") or r.get("Description") or "",
                "source_url": r.get("apply_url") or r.get("Source URL") or r.get("source_url") or "",
            }
            reason = core.real_vacancy_reject_reason(job, {})
            if reason and any(key in reason.lower() for key in ("service/location", "generic region", "not a vacancy")):
                n += 1
        except Exception:
            pass
    return n


def source_counts(sources):
    c = Counter(ctext(s.get("status") or "Blank") for s in sources)
    ats = sum(1 for s in sources if ctext(s.get("source_type") or "").startswith("ATS "))
    fresh = sum(1 for s in sources if ctext(s.get("source_type") or "") == "Fresh Job Signal")
    direct = sum(1 for s in sources if ctext(s.get("source_type") or "") == "Fresh Direct Job Page")
    candidate_official = sum(1 for s in sources if ctext(s.get("source_type") or "") == "Candidate Official Source")
    discovered = sum(1 for s in sources if ctext(s.get("source_type") or "") == "Discovered Website")
    return c, ats, fresh, direct, candidate_official, discovered


def build_report(sheet1, sources, meta, candidates, rejected, workflow_name):
    stamp = core.now_ist().isoformat(timespec="seconds")
    open_jobs = [
        r for r in sheet1
        if ctext(r.get("status") or "").lower() == "publish"
        and ctext(r.get("filled") or "").lower() != "yes"
    ]
    active_meta = [
        r for r in meta
        if ctext(r.get("Status") or "").lower() == "active"
        and ctext(r.get("Application Status") or "").lower() == "open"
    ]
    pending_candidates = [r for r in candidates if ctext(r.get("review_status") or "").lower() in ("pending review", "")]
    official_candidates = [r for r in candidates if ctext(r.get("validation_status") or "") == "Official Source Found"]
    linkedin_candidates = [r for r in candidates if "linkedin" in ctext(r.get("source_type") or "").lower()]
    status_counts, ats_count, fresh_count, direct_count, candidate_source_count, discovered_count = source_counts(sources)

    rows = []
    rows.append(["Overview", "Report generated", stamp, "Asia/Kolkata time"])
    rows.append(["Overview", "Workflow", workflow_name, "Generated by V5"])
    rows.append(["Verified output", "Website-ready open jobs", len(open_jobs), "Strict verified rows in Sheet1"])
    rows.append(["Verified output", "Internal active jobs", len(active_meta), "Open rows in _CollectorMeta"])
    rows.append(["Verified output", "Cleaned fake rows", count_fake_rows(sheet1) + count_fake_rows(meta), "Should remain 0 after cleanup"])
    rows.append(["Candidate pipeline", "CandidateJobs total", len(candidates), "Signals saved for review; not auto-published"])
    rows.append(["Candidate pipeline", "Pending review", len(pending_candidates), "Manual review queue"])
    rows.append(["Candidate pipeline", "Official source found", len(official_candidates), "Candidate signals resolved to official source"])
    rows.append(["Candidate pipeline", "LinkedIn company-listed signals", len(linkedin_candidates), "Signal only; final website never links to LinkedIn"])
    rows.append(["Candidate pipeline", "RejectedJobs total", len(rejected), "Fake/expired/content/service/job-board rejects"])
    rows.append(["Sources", "Total sources", len(sources), "Includes active, warning, inactive, rejected"])
    rows.append(["Sources", "Active sources", status_counts.get("Active", 0), "Eligible for collector"])
    rows.append(["Sources", "Warning sources", status_counts.get("Warning", 0), "Temporary check failures"])
    rows.append(["Sources", "Inactive sources", status_counts.get("Inactive", 0), "Timed out/unreachable repeatedly"])
    rows.append(["Sources", "Rejected sources", status_counts.get("Rejected", 0), "Blocked from collector"])
    rows.append(["Sources", "ATS sources", ats_count, "Rows where source_type starts with ATS"])
    rows.append(["Sources", "Fresh Job Signal sources", fresh_count, "Fresh-discovered sources"])
    rows.append(["Sources", "Fresh Direct Job Page sources", direct_count, "Direct job pages discovered"])
    rows.append(["Sources", "Candidate Official Source rows", candidate_source_count, "Added from CandidateJobs resolver"])
    rows.append(["", "", "", ""])

    for company, count in count_by(open_jobs, "employer_name").most_common(20):
        rows.append(["Verified jobs by employer", company, count, "Sheet1 publish rows"])
    rows.append(["", "", "", ""])

    for category, count in count_by(open_jobs, "category").most_common(20):
        rows.append(["Verified jobs by category", category, count, "Sheet1 publish rows"])
    rows.append(["", "", "", ""])

    for r in open_jobs[:30]:
        rows.append(["Verified live jobs", ctext(r.get("title")), ctext(r.get("employer_name")), " | ".join(x for x in [ctext(r.get("location")), ctext(r.get("category")), ctext(r.get("apply_type")), ctext(r.get("expiry_date"))] if x)])
    rows.append(["", "", "", ""])

    # Show top candidates for stakeholder output.
    candidates_sorted = sorted(candidates, key=lambda r: int(ctext(r.get("verification_score") or "0") or 0), reverse=True)
    for r in candidates_sorted[:40]:
        rows.append(["Top candidate jobs", ctext(r.get("role")), ctext(r.get("company") or "Unknown"), " | ".join(x for x in [ctext(r.get("source_type")), ctext(r.get("validation_status")), "score " + ctext(r.get("verification_score"))] if x)])
    rows.append(["", "", "", ""])

    for reason, count in count_by(rejected, "reject_reason").most_common(20):
        rows.append(["Rejected reason summary", reason, count, "RejectedJobs"])

    return [REPORT_HEADERS] + rows


def update_report(workflow_name):
    sheet_id = os.environ.get("GOOGLE_SHEET_ID", "")
    if not sheet_id:
        raise RuntimeError("Missing GOOGLE_SHEET_ID")
    sheet_tab = os.environ.get("GOOGLE_SHEET_TAB", "Sheet1")
    source_tab = os.environ.get("GOOGLE_SOURCES_TAB", "Sources")
    meta_tab = os.environ.get("GOOGLE_META_TAB", "_CollectorMeta")
    candidate_tab = os.environ.get("GOOGLE_CANDIDATE_TAB", "CandidateJobs")
    rejected_tab = os.environ.get("GOOGLE_REJECTED_TAB", "RejectedJobs")
    report_tab = os.environ.get("GOOGLE_REPORT_TAB", "AutomationOutput")

    svc = core.sheet_service()
    sheet1 = read_records_safe(svc, sheet_id, sheet_tab)
    sources = read_records_safe(svc, sheet_id, source_tab)
    meta = read_records_safe(svc, sheet_id, meta_tab)
    candidates = read_records_safe(svc, sheet_id, candidate_tab)
    rejected = read_records_safe(svc, sheet_id, rejected_tab)

    output = build_report(sheet1, sources, meta, candidates, rejected, workflow_name)
    core.get_sheet_properties(svc, sheet_id, report_tab, create_if_missing=True)
    core.ensure_sheet_columns(svc, sheet_id, report_tab, len(REPORT_HEADERS))
    svc.spreadsheets().values().clear(spreadsheetId=sheet_id, range=f"'{report_tab}'!A:Z", body={}).execute()
    svc.spreadsheets().values().update(
        spreadsheetId=sheet_id,
        range=f"'{report_tab}'!A1:D{len(output)}",
        valueInputOption="RAW",
        body={"values": output},
    ).execute()
    print("=" * 80)
    print(f"AutomationOutput V5 report updated: {len(output)-1} rows")
    print(f"Website-ready jobs: {len(sheet1)}")
    print(f"CandidateJobs: {len(candidates)}")
    print(f"RejectedJobs: {len(rejected)}")
    print("=" * 80)


def self_test():
    sheet1 = [{"title": "Junior Architect", "status": "publish", "filled": "no", "employer_name": "Example Architects", "category": "Architecture", "location": "Mumbai|India"}]
    sources = [{"status": "Active", "source_type": "Seed Website"}, {"status": "Rejected", "source_type": "Fresh Job Signal"}, {"status": "New", "source_type": "Candidate Official Source"}]
    candidates = [{"role": "Junior Architect", "company": "Example Architects", "source_type": "LinkedIn Company Signal", "validation_status": "Signal Only", "verification_score": "65", "review_status": "Pending Review"}]
    rejected = [{"reject_reason": "Service/location landing page, not a job vacancy"}]
    report = build_report(sheet1, sources, [], candidates, rejected, "self-test")
    joined = "\n".join(" ".join(map(str, row)) for row in report)
    assert "CandidateJobs total" in joined
    assert "Website-ready open jobs" in joined
    assert "RejectedJobs total" in joined
    assert "LinkedIn company-listed signals" in joined
    print("REPORT OUTPUT SELF TEST PASSED")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--self-test", action="store_true")
    parser.add_argument("--workflow", default="manual")
    args = parser.parse_args()
    if args.self_test:
        self_test()
    else:
        update_report(args.workflow)


if __name__ == "__main__":
    main()
